POST http://localhost:8000/member/register
Content-Type: application/x-www-form-urlencoded

mobile=888888


###
POST http://localhost:8000/member/send-code
Content-Type: application/x-www-form-urlencoded

mobile=13000000001

###
POST http://localhost:8000/member/login
Content-Type: application/json

{
  "mobile": "13000000001",
  "code": "8888"
}

###
POST http://localhost:8000/member/count
Content-Type: application/json
token: 123

###
POST http://localhost:8001/passenger/save
Content-Type: application/json

{
  "memberId": "111",
  "name": "SGFSWE4G",
  "idCard": "33333",
  "type": "1"
}

