GET http://localhost:8000/admin/station/query-list?page=1&pageSize=10
Content-Type: application/json
token: {{token}}



{
  "dailyTrainTicketId":1998020437350682624,
  "date":1766361600000,
  "end":"峨眉",
  "start":"成都南",
  "tickets": [{
    "passengerId":1991146838572535808,
    "passengerIdCard":"42572727",
    "passengerName":"ycy",
    "passengerType":"1",
    "seatTypeCode":"1"
  }],
  "trainCode":"C4033"
}
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE3NjU5NzE4NjEsIm1vYmlsZSI6IjEzMDAwMDAwMDAwIiwiaWQiOjE5OTA3Mzk5NDgzNjk3NDM4NzIsImV4cCI6MTc2NjA1ODI2MSwiaWF0IjoxNzY1OTcxODYxfQ.xz_xAPkL2FPZa5dt732_yYd-9a0n590bcE7UTdYubTk