server:
  port: 8002
ypj:
  db:
    database: train_business
    un: train_business
cache:
  pre_name:
spring:
  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: train_cache_
      cache-null-values: false
      time-to-live: 60s